package test.model;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_name
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    private String authorityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_describe
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    private String authorityDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.id
     *
     * @return the value of authority.id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.id
     *
     * @param id the value for authority.id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_name
     *
     * @return the value of authority.authority_name
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_name
     *
     * @param authorityName the value for authority.authority_name
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName == null ? null : authorityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_describe
     *
     * @return the value of authority.authority_describe
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public String getAuthorityDescribe() {
        return authorityDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_describe
     *
     * @param authorityDescribe the value for authority.authority_describe
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public void setAuthorityDescribe(String authorityDescribe) {
        this.authorityDescribe = authorityDescribe == null ? null : authorityDescribe.trim();
    }
}