package test.model;

public class RelationalUserAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relational_user_authority.id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relational_user_authority.user_id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relational_user_authority.authority_id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    private Long authorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relational_user_authority.id
     *
     * @return the value of relational_user_authority.id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relational_user_authority.id
     *
     * @param id the value for relational_user_authority.id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relational_user_authority.user_id
     *
     * @return the value of relational_user_authority.user_id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relational_user_authority.user_id
     *
     * @param userId the value for relational_user_authority.user_id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relational_user_authority.authority_id
     *
     * @return the value of relational_user_authority.authority_id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public Long getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relational_user_authority.authority_id
     *
     * @param authorityId the value for relational_user_authority.authority_id
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    public void setAuthorityId(Long authorityId) {
        this.authorityId = authorityId;
    }
}