package test.dao;

import java.util.List;
import test.model.Authority;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    Authority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    List<Authority> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int updateByPrimaryKey(Authority record);
}