package test.dao;

import java.util.List;
import test.model.OauthCode;

public interface OauthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int insert(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    List<OauthCode> selectAll();
}