package test.dao;

import java.util.List;
import test.model.OauthClientDetails;

public interface OauthClientDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int deleteByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int insert(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    OauthClientDetails selectByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    List<OauthClientDetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int updateByPrimaryKey(OauthClientDetails record);
}