package test.dao;

import java.util.List;
import test.model.RelationalUserAuthority;

public interface RelationalUserAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relational_user_authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relational_user_authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int insert(RelationalUserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relational_user_authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    RelationalUserAuthority selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relational_user_authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    List<RelationalUserAuthority> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relational_user_authority
     *
     * @mbg.generated Thu Nov 07 13:31:59 CST 2019
     */
    int updateByPrimaryKey(RelationalUserAuthority record);
}